### ISSUE TITLE
May need to be updated

### ISSUE THREAD

**Issue by gsulshski** [hacctarr/homebridge-tcc-fan#2]
When I updated to homebridge v1.0.2 ,  I now get the error message below.
I also see many warning... deprecated message when I am compiling homebridge-tcc-fan.

DS Failed: Error: Cannot update reachability on non-bridged accessory!
    at Accessory._this.updateReachability (/Users/.local/lib/npm/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:399:13)
    at PlatformAccessory.updateReachability (/Users/.local/lib/npm/lib/node_modules/homebridge/src/platformAccessory.ts:124:34)
    at /Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/index.js:140:44
    at Session.<anonymous> (/Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/lib/tcc.js:33:9)
    at _fulfilled (/Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/node_modules/q/q.js:787:54)
    at /Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/node_modules/q/q.js:816:30
    at Promise.promise.promiseDispatch (/Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/node_modules/q/q.js:749:13)
    at /Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/node_modules/q/q.js:557:44
    at flush (/Users/.local/lib/npm/lib/node_modules/homebridge-tcc-fan/node_modules/q/q.js:108:17)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by gsulshski** [comment]
With home bridge v1.0.4,  all error messages went away and noted a fix for updateReachability in this version
